### ISSUE TITLE
zabbix on docker

### ISSUE THREAD

**Issue by empereira** [Galvy/Template-Samba4-AD#1]
hello,

Did you test this template only on the physical server or via docker as well?

Btw, nice work!!!

**Comment by Galvy** [comment]
hello,
only with physical server.

Thanks!!

**Comment by Galvy** [comment]
> hello,
> 
> Did you test this template only on the physical server or via docker as well?
> 
> Btw, nice work!!!

hello,
only with physical server.

Thanks!!
